create table categoria (
	id_categoria INT,
	descripcion VARCHAR(50),
	nombre VARCHAR(50),
	cantidad_de_productos VARCHAR(50)
);
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (1, 'Wiberg Super Cure', 'MIRALAC ANTACID', '6481');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (2, 'Wasabi Paste', 'Ropinirole', '1600');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (3, 'Bread Crumbs - Japanese Style', 'ShopRite Allergy', '6477');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (4, 'Kahlua', 'Fosrenol', '7755');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (5, 'Sprouts Dikon', 'rocuronium bromide', '9347');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (6, 'Lamb - Leg, Boneless', 'Vital Male Sexual Energy', '0462');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (7, 'Beef - Inside Round', 'Standardized Mite D. farinae', '1007');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (8, 'Lid - 0090 Clear', 'Valsartan and hydrochlorothiazide', '5214');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (9, 'Lamb - Whole, Fresh', 'SUNFLOWER SEED', '7332');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (10, 'Shrimp - 16/20, Peeled Deviened', 'OXYGEN', '3633');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (11, 'Ham - Black Forest', 'Reclaim Radiance', '2520');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (12, 'Crackers - Water', 'Beleodaq', '7993');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (13, 'Uniform Linen Charge', 'APAP', '2757');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (14, 'Capicola - Hot', 'Pert Plus Dandruff Plus', '7436');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (15, 'Beef - Salted', 'Sword Fish', '3409');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (16, 'Bread - Roll, Whole Wheat', 'good neighbor pharmacy milk of magnesia', '3398');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (17, 'Squash - Pattypan, Yellow', 'Exchange Select Sport Sunscreen', '2512');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (18, 'Muffin Mix - Blueberry', 'Librium', '0173');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (19, 'Pork - Bacon, Sliced', 'Healthy Accents Triple Antibiotic', '2500');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (20, 'Longos - Penne With Pesto', 'Tussin Original', '8633');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (21, 'Jello - Assorted', 'Verticalm', '8129');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (22, 'Tomatoes - Vine Ripe, Yellow', 'Oxycodone and Acetaminophen', '0503');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (23, 'Lamb - Leg, Boneless', 'MORUS ALBA POLLEN', '9463');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (24, 'Flour - Chickpea', 'gemcitabine', '6714');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (25, 'Rosemary - Fresh', 'METHYLPREDNISOLONE', '7912');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (26, 'Beef - Bresaola', 'HypoTears', '4543');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (27, 'Onions - Red Pearl', 'Lyrica', '1611');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (28, 'Chicken - Soup Base', 'Irbesartan', '2817');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (29, 'Mushroom - Enoki, Fresh', 'Anti Acne Calming Corrector', '0400');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (30, 'Chocolate - Compound Coating', 'PURELL Advanced Instant Hand Sanitizer Fragrance Free', '0648');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (31, 'Coffee Swiss Choc Almond', 'Fenofibrate', '8633');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (32, 'Wine - Ruffino Chianti Classico', 'Ferric Subsulfate', '0190');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (33, 'Muffin Hinge Container 6', 'Tretinoin', '4393');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (34, 'Calaloo', 'Perindopril Erbumine', '9758');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (35, 'Cinnamon - Ground', 'Savella', '4159');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (36, 'Pepper - Green, Chili', 'Labetalol hydrochloride', '5093');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (37, 'Bread - Mini Hamburger Bun', 'PONDS', '6140');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (38, 'Tomatoes', 'Amrix', '4346');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (39, 'Wine - Pinot Noir Mondavi Coastal', 'Cialis', '9872');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (40, 'Goat - Leg', 'Adenosine', '0315');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (41, 'Chocolate - Pistoles, White', 'Aspirin', '0164');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (42, 'Turkey - Breast, Boneless Sk On', 'Nicotine', '0329');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (43, 'Wine - Zinfandel Rosenblum', 'CENTER-AL - CYNODON DACTYLON POLLEN', '1132');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (44, 'Persimmons', 'Amlodipine and Atorvastatin', '0960');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (45, 'Butter Sweet', 'Corn Removers', '6846');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (46, 'Pastry - Banana Tea Loaf', 'Technetium Tc99m Generator', '2142');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (47, 'Pumpkin', 'Zep Professional Z-Verdant Foaming', '9782');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (48, 'Wiberg Super Cure', 'Ulta Pomegranate Lime Anti-Bacterial Deep Cleansing', '7229');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (49, 'Ranchero - Primerba, Paste', 'Rubus', '2348');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (50, 'Arctic Char - Fresh, Whole', 'Acid Reducer', '3036');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (51, 'Soup - Campbells, Lentil', 'Naproxen', '9292');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (52, 'Sprouts - Brussel', 'Olanzapine', '6278');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (53, 'Goat - Whole Cut', 'ROBITUSSIN NIGHT TIME COUGH AND COLD', '8027');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (54, 'Wine - Niagara,vqa Reisling', 'Propylthiouracil', '5385');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (55, 'Lighter - Bbq', 'ADRENOCORTICOTROPHIN', '7264');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (56, 'Ketchup - Tomato', 'Technetium Tc 99m Medronate', '8171');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (57, 'Pepper - Scotch Bonnet', 'Apatite Cucurbita', '3329');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (58, 'Shortbread - Cookie Crumbs', 'Pepcid', '1657');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (59, 'Radish - Black, Winter, Organic', 'Betamethasone Dipropionate', '9982');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (60, 'Tray - Foam, Square 4 - S', 'RevitaDERM Wound Care', '7396');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (61, 'Mcguinness - Blue Curacao', 'Head and Shoulders', '8725');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (62, 'Rice Pilaf, Dry,package', 'HYDROXYUREA', '5087');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (63, 'Vector Energy Bar', 'ESIKA', '2663');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (64, 'Sprouts - Baby Pea Tendrils', 'Nicardipine Hydrochloride', '6573');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (65, 'Quiche Assorted', 'Up and Up Cold Flu Relief', '4145');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (66, 'Iced Tea Concentrate', 'AeroGreen Antibac', '7676');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (67, 'Salt - Table', 'Neutrogena Age Defense Anti Oxidant Daily Moisturizer', '3402');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (68, 'Cheese Cloth No 100', 'CardinalHealth bathing wipe with dimethicone', '4027');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (69, 'Mustard - Pommery', 'AUREOBASIDIUM PULLULANS VAR PULLULANS', '9709');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (70, 'Chinese Foods - Chicken', 'Xopenex', '9851');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (71, 'Foam Espresso Cup Plain White', 'Freshscent Anti-Bacterial', '4192');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (72, 'Sausage - Meat', 'Chlorpromazine Hydrochloride', '6359');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (73, 'Myers Planters Punch', 'CELEBREX', '0396');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (74, 'Pork Salted Bellies', 'LABETALOL HYDROCHLORIDE', '7976');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (75, 'Bread - Crusty Italian Poly', 'LANEIGE BB Cushion no.23', '0154');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (76, 'Wine - Sawmill Creek Autumn', 'Atovaquone and Proguanil Hydrochloride', '1685');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (77, 'Pastry - Baked Scones - Mini', 'Hydrocortisone', '1064');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (78, 'Lamb - Whole, Frozen', 'AZITHROMYCIN', '7008');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (79, 'Sauce - Apple, Unsweetened', 'Melvita NECTAR DE ROSES BB Sunscreen BROAD SPECTRUM SPF 15 NUDE ROSE', '7920');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (80, 'Wine - Charddonnay Errazuriz', 'Arixtra', '1173');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (81, 'Wine - Red, Harrow Estates, Cab', 'Gabapentin', '2758');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (82, 'Dc - Frozen Momji', 'ED A-HIST DM', '5224');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (83, 'Jello - Assorted', 'HAND SANITIZING', '6280');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (84, 'Veal - Leg, Provimi - 50 Lb Max', 'Mirapharm-22', '4370');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (85, 'Turnip - Wax', 'Nardil', '4738');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (86, 'Lamb Rack - Ontario', 'OralSoothe', '6553');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (87, 'Corn - Mini', 'Banana Boat UltraMist Kids SPF 50 Factor de Proteccion Solar 50', '2885');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (88, 'Pork - Suckling Pig', 'Shopko Antibacterial Deep Cleansing Hand', '1440');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (89, 'Vol Au Vents', 'LBEL COULEUR LUXE AMPLIFIER XP', '7249');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (90, 'Beef - Tenderloin - Aa', 'Precose', '6691');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (91, 'Tandoori Curry Paste', 'Attention Span', '5589');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (92, 'Beer - Sleemans Honey Brown', 'Paroxetine', '2980');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (93, 'Island Oasis - Banana Daiquiri', 'Eco-Clean Elite', '2336');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (94, 'Filo Dough', 'Stool Softener', '9452');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (95, 'Wine - Delicato Merlot', 'Gas Relief', '4957');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (96, 'The Pop Shoppe - Lime Rickey', 'BIOTENE', '0047');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (97, 'Salmon - Sockeye Raw', 'Dicloxacillin Sodium', '3899');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (98, 'Bread - Rolls, Rye', 'DIPYRIDAMOLE', '8756');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (99, 'Mushroom - Oyster, Fresh', 'Lisinopril', '2170');
insert into categoria (id_categoria, descripcion, nombre, cantidad_de_productos) values (100, 'Shrimp - Black Tiger 16/20', 'Fiber', '2380');
